[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm", "chromium"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd apps/api && pnpm run build"]

[start]
cmd = "cd apps/api && node dist/server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium/bin/chromium"
